### ISSUE TITLE
Arduino board ID

### ISSUE THREAD

**Issue by netta-hub** [neural-electrophysiology-tool-team/reptilearn#16]
on the last step of the arduino-cli installation this line is written:

arduino-cli core install <board ID>

how do I get to the board ID?

thnx

**Comment by eisental** [comment]
Running `arduino-cli core list --all` should print all existing IDs (left column). For "Arduino Nano Every" the right ID is arduino:megaavr. For other boards find the ID according to the Name column. By the way, we moved the repository to here: https://github.com/EvolutionaryNeuralCodingLab/reptiLearn. Any updates will be done there from now on.
